### ISSUE TITLE
test code does not work

### ISSUE THREAD

**Issue by bybybybyb** [apsdehal/Shortest-Adversial-Path-Architecture#1]
Hi,

I am working on connecting our code with the server and now I found the test code you provided does not work. It seems that after the first recv (which in your instructions start/end and the whole graph are sent and at the client side it is divided in several reads since in the test code each time only 1024 characters are read), we are receiving empty strings rather than "x y cost" or "y" as in the instruction. I tried it with Node.js 4.6.0 and 0.12.7 but neither works.

Sincerely,
Boyuan

**Comment by apsdehal** [comment]
Can you try the following steps? Open three terminals and then:
`node index.js` in first
`python test-client.py` in second
`python test-adversary.py` in third.

Is it working?

**Comment by apsdehal** [comment]
I have just tried the same and seems to be working fine for me.

**Comment by bybybybyb** [comment]
I used the exact way to run the code before.
I added debug code in two testers to see what they received.

![image](https://cloud.githubusercontent.com/assets/2519878/19223491/5681b288-8e3f-11e6-9eea-813812a3803c.png)

![image](https://cloud.githubusercontent.com/assets/2519878/19223492/6466b8bc-8e3f-11e6-8a9f-cb9d1fa03d86.png)

![image](https://cloud.githubusercontent.com/assets/2519878/19223497/6f311c4c-8e3f-11e6-9237-24de7a376344.png)

Which Python version do you use?

**Comment by apsdehal** [comment]
I am using 2.7. I tried reproducing the issue, but couldn't. I guess mostly issue is that clients are not sending data in your case. Try adding `console.log(data.toString())` at https://github.com/apsdehal/Shortest-Adversial-Path-Architecture/blob/master/src/connection-handler.js#L55 and https://github.com/apsdehal/Shortest-Adversial-Path-Architecture/blob/master/src/connection-handler.js#L73

**Comment by apsdehal** [comment]
Also can try using netcat instead of test-clients to check if issue is somewhere on your side. 
Try the following steps:
`node index.js`
In separate terminals `nc localhost 5000` and in other one `nc localhost 5000` and send 84 from first one and `165 84` from other one. Check if they are received on both ends.

**Comment by bybybybyb** [comment]
The server only received the step sent by test-player.py, which is 84:

> node index.js 
> Server started
> Waiting for player
> Waiting for adversary
> 84
> Player has 119.998 seconds left

then the connection was broken with the same exception in the previous screenshot.

I printed the data test-adversary.py was going to send and it looks good. Both two clients have not thrown exceptions about the tcp connection itself so I guess there is something wrong with the server side on receiving adversary's data.

This bug was mentioned by Anurag Dhaipule before in his e-mail to the mailing list but seems you did not notice that. I am not sure if it is something wrong with my laptop or not, but since someone else had encountered the same problem I guess it is very unlikely.

**Comment by bybybybyb** [comment]
Using netcat I found after sending 84 from the first (player) session, the server went down with that exception. I have no chance to send another cmd from the second (adversary) session.

**Comment by bybybybyb** [comment]
Are you sure the code you tested just now is the same as the code you committed?

**Comment by apsdehal** [comment]
Yes, as soon as I make a major change I commit it always.

**Comment by apsdehal** [comment]
![image](https://cloud.githubusercontent.com/assets/3616806/19223678/91d20a50-8e43-11e6-9565-8744ed4817bf.png)

Here is a picture of working code on my machine.

**Comment by apsdehal** [comment]
Did you get file information on netcat?

**Comment by bybybybyb** [comment]
What do you mean by file information?

I guess there is something wrong with this function in game-data-manager.js:

![image](https://cloud.githubusercontent.com/assets/2519878/19223820/fff1808a-8e46-11e6-9277-c67a16d3499e.png)

by which I got:

![image](https://cloud.githubusercontent.com/assets/2519878/19223825/128a794a-8e47-11e6-89cd-374a2ee451e3.png)

**Comment by apsdehal** [comment]
This is fine. It means if y is not passed, it is a single point to which player wants to move, thus edge's y becomes x and edge's x becomes player one's position, which means we have to validate if player is moving to correct y position.

**Comment by apsdehal** [comment]
File information, the initial graph information.

**Comment by bybybybyb** [comment]
As you can see, by "y = x", y became a reference to x rather than a copy of x's value. When "x = this.playerOnePosition" was ran, y got the value of player one's position and x was destructed. Then they were passed into following functions and finally we got this.adjacencyList[x] be undefined.

**Comment by bybybybyb** [comment]
I did got the graph information.

**Comment by apsdehal** [comment]
Hey, can you run `nc vps.apsdehal.in 5000` in two terminals.

**Comment by apsdehal** [comment]
And send `84` and `165 84` from both of them

**Comment by bybybybyb** [comment]
Amazing, your code works on your own vps.

**Comment by apsdehal** [comment]
I am adding you on facebook, so we can easily chat.

**Comment by bybybybyb** [comment]
sure

**Comment by bybybybyb** [comment]
Nice. It was fixed.

You'd better send an e-mail to the mailing list for others to pull the repo again.
